### ISSUE TITLE
results!!!

### ISSUE THREAD

**Issue by despoinamusica39** [impliedchaos/mopidy-youtubemusic#1]
hello and happy blessed year.tell me please as you know youtube music api permit very few albums and songs...do you know if there is some way to increase unlimited results?thanks a lot!

**Comment by impliedchaos** [comment]
You can try setting the `playlist_item_limit` option to a higher value than the default of 100.  The issue is one of speed: to increase the number of entries returned requires repeated queries to Youtube Music which takes time.

**Comment by impliedchaos** [comment]
I'm sorry, I just read the title, and realized you meant the search results were limited.  My search results have always been pretty accurate without much missing.  Do you have an example of a query that's returning too few results?

**Comment by despoinamusica39** [comment]
hello from Greece!thanks where answer me!very kind.look not appear thousand songs...more less 200 just

**Comment by impliedchaos** [comment]
Sorry, I think that's just a limitation of YouTube Music.  I think you'd need to contact Google/YouTube about that.
