### ISSUE TITLE
Duplicating work

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [impliedchaos/mopidy-youtubemusic#2]
Hello,

You've done amazing work on this extension.
I've been dealing with Corona for the past month, which is why I was unresponsive.
Now that I'm better I'd like to continue working on Mopidy-YTMusic.

Since you seem to be intending to go forth with your own fork, it'd be pretty difficult for me not to lift code from your fork.
(I mean that as a compliment, you already solved pretty much every open bug).
So basically I'd like to offer to merge these projects, where we both would be contributors with write access to repo.
That'd make sense I think, since there's no need for two extensions doing the same thing with the main difference being maintainers.
For reasons such as pride and my repo having stars already, I'd prefer to merge this repo into mine and add you as a collaborator.
However these reasons are pretty weak and your repo has better name (I suck at naming things mostly).
So what do you think? Can we collaborate on this?

**Comment by impliedchaos** [comment]
Hi Tomas,

I'm glad you're better and sorry that you've been sick.  And yes, I'd be happy to merge back into yours.  I thought maybe I was overstepping my bounds with that pull request so I just hard forked instead.  Also I made a lot of changes that I forgot to list reasons for.

Let me know what steps we need to do to get things merged.

Thanks!
Dave

**Comment by OzymandiasTheGreat** [comment]
First, sorry I'm not responding in a timely manner. I'm still a bit feverish, looks like I got a secondary infection.

Your thinking is correct, it would be more manageable if it was multiple pull requests doing 1-2 things each.
However refactoring was badly needed and bugfixes I'd have to do anyway, so that's half the pull request.
Also the code looks fine and features are welcome.
Anyway, I sent you an invite to collaborate on the main repo, since you seem to have the time and motivation to work on this.

As for the pull request, just 2 things. Please resolve conflicts with the master branch and is it ready for release? Looks ready to me, but you know better.
I'm gonna bump version to 0.2, because this'll be a pretty major release.

**Comment by impliedchaos** [comment]
Don't worry about it.  Just focus on getting better.

And thanks for the invite!  I'll resolve the conflicts and merge the PR today.  I'm gonna do a little more testing after the merge to make sure it's ready for release, and then I'll let you know.   Also, I'll archive this fork to reduce confusion.
